[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true

[dependencies]
forge-std = { git = "https://github.com/foundry-rs/forge-std", version = "v1.8.2" }
openzeppelin-contracts = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts", version = "v5.0.0" }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

[fuzz]
runs = 1000

[invariant]
runs = 256
depth = 32
fail_on_revert = false 