[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# Monad Network Configuration
[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"

[etherscan]
monad_testnet = { key = "${MONAD_API_KEY}", url = "https://testnet-explorer.monad.xyz/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config 